### ISSUE TITLE
I must be missing something

### ISSUE THREAD

**Issue by zoggins** [ssshake/pi-uhf-tv-station#11]
I followed all the instructions in the readme and the app doesn't do anything that I can tell (nothing shows up in the "display").  Maybe I have my video directories the wrong way.  I know very little about node.js, so I am having a hard time debugging the problem.  Any help would be appreciated.  Thanks.

**Comment by zoggins** [comment]
I am not sure I understand how to build playlists, are they just folders of videos?

**Comment by zoggins** [comment]
Well I learned that I can get videos to play (without sound for some reason) by calling the api directly.  So it looks like the app and api are not communicating

**Comment by zoggins** [comment]
well i figured out to change the 10.0.0.20 IP in the RemoteControl.vue file, but its still not working.

**Comment by zoggins** [comment]
solved my own problems, forgot to recompile the app.  thanks!

**Comment by ssshake** [comment]
Hey I'm sorry, I forgot to bring in the IP from configuration, rather than having it hard coded.

I also planned to change the express server so that the vue application was served behind a route on it's own port instead of having to run two separate processes. 

I just got lazy and hadn't done that part yet.

**Comment by zoggins** [comment]
No worries, I sorted it out.  Great project!
